"""
arifOS L5: Architect Agent
==========================
The Architect plans and designs approaches to user queries.

Role: Strategic planning, approach design, task decomposition
Stage: 333_REASON (Reasoning phase)

Governed by:
- F2 Truth (τ ≥ 0.99): Plans must be factually grounded
- F4 Clarity (ΔS ≤ 0): Plans must reduce confusion
- F8 Genius (G ≥ 0.80): Plans must be intelligently structured

Physics Basis:
- Information geometry (Fisher-Rao) for truth verification
- Shannon entropy for clarity measurement
- Category theory for plan structure

Version: v55.3-L5-alpha
Author: Muhammad Arif bin Fazil
License: AGPL-3.0-only
"""

import json
from dataclasses import dataclass, field
from datetime import datetime, timezone
from typing import Any, Optional

from .base_agent import AgentOutput, BaseAgent, FloorScores, Verdict


@dataclass
class PlanStep:
    """A single step in an execution plan."""

    step_number: int
    action: str
    description: str
    agent_responsible: str  # Which agent executes this
    inputs: list[str]
    outputs: list[str]
    estimated_complexity: str  # "low", "medium", "high"
    floor_requirements: list[str]  # Which floors are critical

    def to_dict(self) -> dict:
        return {
            "step_number": self.step_number,
            "action": action,
            "description": self.description,
            "agent_responsible": self.agent_responsible,
            "inputs": self.inputs,
            "outputs": self.outputs,
            "estimated_complexity": self.estimated_complexity,
            "floor_requirements": self.floor_requirements,
        }


@dataclass
class ArchitectPlan:
    """
    Structured plan generated by Architect.

    Contains:
    - Goal analysis
    - Task decomposition
    - Agent assignments
    - Risk assessment
    - Constitutional requirements
    """

    query: str
    goal_summary: str
    approach: str
    steps: list[PlanStep]
    risks: list[str]
    constitutional_notes: list[str]
    estimated_total_complexity: str
    requires_human_review: bool
    timestamp: datetime = field(default_factory=lambda: datetime.now(timezone.utc))

    def to_dict(self) -> dict:
        return {
            "query": self.query,
            "goal_summary": self.goal_summary,
            "approach": self.approach,
            "steps": [
                {
                    "step_number": s.step_number,
                    "action": s.action,
                    "description": s.description,
                    "agent_responsible": s.agent_responsible,
                    "inputs": s.inputs,
                    "outputs": s.outputs,
                    "estimated_complexity": s.estimated_complexity,
                    "floor_requirements": s.floor_requirements,
                }
                for s in self.steps
            ],
            "risks": self.risks,
            "constitutional_notes": self.constitutional_notes,
            "estimated_total_complexity": self.estimated_total_complexity,
            "requires_human_review": self.requires_human_review,
            "timestamp": self.timestamp.isoformat(),
        }

    def to_json(self) -> str:
        return json.dumps(self.to_dict(), indent=2)


class Architect(BaseAgent):
    """
    Architect Agent — Strategic Planning
    =====================================

    The Architect analyzes user queries and creates structured
    execution plans for the federation.

    Responsibilities:
    1. Understand the user's goal
    2. Decompose into actionable steps
    3. Assign steps to appropriate agents
    4. Identify risks and constitutional requirements
    5. Flag if human review is needed (F13 Sovereign)

    Output: ArchitectPlan with steps, risks, and governance notes

    Example:
        architect = Architect()
        result = await architect.governed_process({
            "query": "Analyze the oil reserves data and generate report"
        })
        plan = result.response  # ArchitectPlan object
    """

    def __init__(self):
        super().__init__(
            name="Architect", role="Strategic planning and task decomposition", stage="333_REASON"
        )

        # Domain knowledge for better planning
        self._complexity_keywords = {
            "high": ["analyze", "complex", "multiple", "comprehensive", "deep"],
            "medium": ["create", "generate", "process", "evaluate"],
            "low": ["list", "show", "get", "simple", "basic"],
        }

        # Keywords that trigger human review (F13 Sovereign)
        self._human_review_triggers = [
            "delete",
            "remove",
            "permanent",
            "irreversible",
            "financial",
            "medical",
            "legal",
            "personal",
            "confidential",
            "secret",
            "private",
            "commit",
            "deploy",
            "production",
        ]

    def _analyze_complexity(self, query: str) -> str:
        """
        Estimate query complexity.

        Uses keyword matching + heuristics.

        Returns: "low", "medium", or "high"
        """
        query_lower = query.lower()

        # Check for high complexity indicators
        high_count = sum(1 for kw in self._complexity_keywords["high"] if kw in query_lower)
        if high_count >= 2 or len(query.split()) > 30:
            return "high"

        # Check for medium complexity
        medium_count = sum(1 for kw in self._complexity_keywords["medium"] if kw in query_lower)
        if medium_count >= 1 or len(query.split()) > 15:
            return "medium"

        return "low"

    def _needs_human_review(self, query: str) -> bool:
        """
        Check if query requires human review (F13 Sovereign).

        Triggers on:
        - Irreversible actions
        - Sensitive domains (financial, medical, legal)
        - Production deployments
        """
        query_lower = query.lower()
        return any(trigger in query_lower for trigger in self._human_review_triggers)

    def _identify_risks(self, query: str, complexity: str) -> list[str]:
        """
        Identify potential risks in execution.

        Maps to constitutional floors that need attention.
        """
        risks = []
        query_lower = query.lower()

        # Data integrity risks (F1 Amanah)
        if any(kw in query_lower for kw in ["modify", "update", "change", "edit"]):
            risks.append("F1 Amanah: Data modification requires audit trail")

        # Accuracy risks (F2 Truth)
        if any(kw in query_lower for kw in ["analyze", "calculate", "predict"]):
            risks.append("F2 Truth: Analysis requires source verification")

        # Complexity risks (F4 Clarity)
        if complexity == "high":
            risks.append("F4 Clarity: High complexity may increase entropy")

        # Stakeholder risks (F6 Empathy)
        if any(kw in query_lower for kw in ["user", "customer", "patient", "client"]):
            risks.append("F6 Empathy: Stakeholder impact requires care")

        return risks

    def _generate_constitutional_notes(self, query: str, needs_review: bool) -> list[str]:
        """Generate constitutional compliance notes."""
        notes = []

        notes.append("All outputs must pass 13 floors before SEAL")

        if needs_review:
            notes.append("F13 Sovereign: Human review REQUIRED before execution")

        # Always note Anti-Hantu
        notes.append("F9 Anti-Hantu: No consciousness claims in outputs")

        return notes

    def _create_plan_steps(self, query: str, complexity: str) -> list[PlanStep]:
        """
        Create execution steps for the federation.

        Maps query to appropriate agents:
        - Architect: Planning (this agent)
        - Engineer: Implementation
        - Auditor: Compliance checking
        - Validator: Final consensus
        """
        steps = []
        query_lower = query.lower()

        # Step 1: Always start with understanding (Architect)
        steps.append(
            PlanStep(
                step_number=1,
                action="UNDERSTAND",
                description="Parse query intent and extract requirements",
                agent_responsible="Architect",
                inputs=["user_query"],
                outputs=["parsed_intent", "requirements"],
                estimated_complexity="low",
                floor_requirements=["F2 Truth", "F4 Clarity"],
            )
        )

        # Step 2: Implementation varies by query type
        if any(kw in query_lower for kw in ["create", "generate", "build", "write"]):
            steps.append(
                PlanStep(
                    step_number=2,
                    action="GENERATE",
                    description="Create the requested artifact",
                    agent_responsible="Engineer",
                    inputs=["parsed_intent", "requirements"],
                    outputs=["artifact_draft"],
                    estimated_complexity=complexity,
                    floor_requirements=["F1 Amanah", "F2 Truth", "F8 Genius"],
                )
            )
        elif any(kw in query_lower for kw in ["analyze", "evaluate", "assess"]):
            steps.append(
                PlanStep(
                    step_number=2,
                    action="ANALYZE",
                    description="Perform analysis on provided data/context",
                    agent_responsible="Engineer",
                    inputs=["parsed_intent", "data_context"],
                    outputs=["analysis_results"],
                    estimated_complexity=complexity,
                    floor_requirements=["F2 Truth", "F4 Clarity", "F7 Humility"],
                )
            )
        elif any(kw in query_lower for kw in ["find", "search", "locate", "get"]):
            steps.append(
                PlanStep(
                    step_number=2,
                    action="RETRIEVE",
                    description="Find and retrieve requested information",
                    agent_responsible="Engineer",
                    inputs=["parsed_intent", "search_context"],
                    outputs=["retrieved_data"],
                    estimated_complexity="medium" if complexity == "high" else "low",
                    floor_requirements=["F2 Truth", "F3 Tri-Witness"],
                )
            )
        else:
            # Generic processing
            steps.append(
                PlanStep(
                    step_number=2,
                    action="PROCESS",
                    description="Process the request according to intent",
                    agent_responsible="Engineer",
                    inputs=["parsed_intent"],
                    outputs=["processed_result"],
                    estimated_complexity=complexity,
                    floor_requirements=["F1 Amanah", "F2 Truth"],
                )
            )

        # Step 3: Always audit (Auditor)
        steps.append(
            PlanStep(
                step_number=3,
                action="AUDIT",
                description="Check all 13 floors for compliance",
                agent_responsible="Auditor",
                inputs=["processed_result", "floor_requirements"],
                outputs=["audit_report", "floor_scores"],
                estimated_complexity="low",
                floor_requirements=["F3 Tri-Witness", "F9 Anti-Hantu"],
            )
        )

        # Step 4: Final validation (Validator)
        steps.append(
            PlanStep(
                step_number=4,
                action="VALIDATE",
                description="Tri-Witness consensus and final SEAL/VOID",
                agent_responsible="Validator",
                inputs=["audit_report", "floor_scores"],
                outputs=["final_verdict", "sealed_output"],
                estimated_complexity="low",
                floor_requirements=["F3 Tri-Witness", "F13 Sovereign"],
            )
        )

        return steps

    async def process(self, input_data: dict) -> dict:
        """
        Generate execution plan for the query.

        Args:
            input_data: Dictionary with 'query' key

        Returns:
            Dictionary with 'response' containing ArchitectPlan
        """
        query = input_data.get("query", "")
        context = input_data.get("context", {})

        # Analyze the query
        complexity = self._analyze_complexity(query)
        needs_review = self._needs_human_review(query)
        risks = self._identify_risks(query, complexity)
        notes = self._generate_constitutional_notes(query, needs_review)

        # Generate plan steps
        steps = self._create_plan_steps(query, complexity)

        # Create the plan
        plan = ArchitectPlan(
            query=query,
            goal_summary=f"Execute user request: {query[:100]}{'...' if len(query) > 100 else ''}",
            approach=f"Federation execution with {len(steps)} steps at {complexity} complexity",
            steps=steps,
            risks=risks,
            constitutional_notes=notes,
            estimated_total_complexity=complexity,
            requires_human_review=needs_review,
        )

        # Update floor scores based on planning quality
        # F4 Clarity: Plan reduces entropy (good structure)
        self._floor_scores.f4_clarity = -0.1  # Negative = entropy reduced

        # F2 Truth: Plan is honest about complexity
        self._floor_scores.f2_truth = 0.99

        return {
            "response": plan,
            "plan_dict": plan.to_dict(),
            "complexity": complexity,
            "needs_human_review": needs_review,
        }

    def plan_summary(self, plan: ArchitectPlan) -> str:
        """
        Generate human-readable plan summary.

        For display purposes.
        """
        lines = [
            f"═══ ARCHITECT PLAN ═══",
            f"Goal: {plan.goal_summary}",
            f"Approach: {plan.approach}",
            f"Complexity: {plan.estimated_total_complexity.upper()}",
            f"Human Review: {'REQUIRED' if plan.requires_human_review else 'Not required'}",
            f"",
            f"Steps ({len(plan.steps)}):",
        ]

        for step in plan.steps:
            lines.append(
                f"  {step.step_number}. [{step.agent_responsible}] {step.action}: {step.description}"
            )

        if plan.risks:
            lines.append(f"")
            lines.append(f"Risks ({len(plan.risks)}):")
            for risk in plan.risks:
                lines.append(f"  ⚠️ {risk}")

        if plan.constitutional_notes:
            lines.append(f"")
            lines.append(f"Constitutional Notes:")
            for note in plan.constitutional_notes:
                lines.append(f"  📋 {note}")

        return "\n".join(lines)


# Export
__all__ = ["Architect", "ArchitectPlan", "PlanStep"]
