FROM python:3.10-alpine
WORKDIR /app

# Install dependencies
RUN apk add --no-cache udev ttf-freefont chromium nodejs npm

# Upgrade pip
RUN pip install --upgrade pip

COPY requirements.txt ./
RUN pip install -r requirements.txt
COPY . .
ENV PYTHONPATH=/app
WORKDIR /app/
EXPOSE 8080
CMD ["python", "server.py"]
